### ISSUE TITLE
Cannot find module error after install

### ISSUE THREAD

**Issue by Happy0** [depject/depject-tree#1]
`
[happy0@delta patchwork]$ sudo npm install -g depject-tree
/usr/bin/depject-tree -> /usr/lib/node_modules/depject-tree/index.js
+ depject-tree@1.1.1
updated 1 package in 0.354s
[happy0@delta patchwork]$ depject-tree . node_modules/patchcore
module.js:491
    throw err;
    ^

Error: Cannot find module 'depject/is'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/depject-tree/index.js:8:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
[happy0@delta patchwork]$ 
[happy0@delta patchwork]$ 
`

**Comment by Happy0** [comment]
Ah, it worked after I globally installed depject and libneste.

Should these be part of the package.json for depject-tree? (Note: I've only recently began using nodejs, so I'm not 100% sure what the convention is.)
